# Generated by Django 3.1.1 on 2020-11-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_end', models.CharField(default='right', max_length=200)),
                ('left_end', models.CharField(default='left', max_length=200)),
                ('feature_name', models.CharField(default='Name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_subject', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_text', models.CharField(default='', max_length=1000)),
                ('int_place', models.IntegerField()),
                ('str_place', models.CharField(default='', max_length=40)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('target_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.featurelabels')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('profilemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profilePresntaion.profilemodel')),
                ('trials_string_list', models.CharField(default='', max_length=800)),
                ('trials_responses_list', models.CharField(default='', max_length=800)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.experiment')),
            ],
            bases=('profilePresntaion.profilemodel',),
        ),
    ]
