# Generated by Django 3.1.1 on 2020-09-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_end', models.CharField(default='a', max_length=200)),
                ('left_end', models.CharField(default='b', max_length=200)),
                ('feature_name', models.CharField(default='c', max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.profilemodel')),
            ],
        ),
    ]
