# Generated by Django 3.1.1 on 2020-10-14 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_end', models.CharField(default='right', max_length=200)),
                ('left_end', models.CharField(default='left', max_length=200)),
                ('feature_name', models.CharField(default='Name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('target_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.featurelabels')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.profilemodel')),
            ],
        ),
    ]
