# Generated by Django 3.1.1 on 2020-09-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_end', models.CharField(default='a', max_length=200)),
                ('left_end', models.CharField(default='b', max_length=200)),
                ('feature_name', models.CharField(default='c', max_length=200)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('a_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.newfeature')),
            ],
        ),
    ]
