# Generated by Django 3.1.1 on 2020-11-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructions',
            new_name='Instruction',
        ),
    ]
