# Generated by Django 3.1.1 on 2020-09-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0002_newfeature_newprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newprofile',
            name='a_feature',
        ),
        migrations.DeleteModel(
            name='newFeature',
        ),
        migrations.DeleteModel(
            name='NewProfile',
        ),
    ]
