# Generated by Django 3.1.1 on 2020-10-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0003_auto_20200925_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_end', models.CharField(default='right', max_length=200)),
                ('left_end', models.CharField(default='left', max_length=200)),
                ('feature_name', models.CharField(default='Name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('target_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.featurelabels')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.profilemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
