# Generated by Django 3.1.1 on 2020-11-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0003_experiment_phases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='str_place',
        ),
        migrations.CreateModel(
            name='ExperimentPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('phase_place', models.IntegerField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.experiment')),
            ],
        ),
        migrations.AddField(
            model_name='instruction',
            name='str_phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.experimentphase'),
        ),
    ]
