# Generated by Django 3.1.1 on 2020-11-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0005_auto_20201108_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='current_phase',
            field=models.CharField(default='Initial Phase', max_length=30),
        ),
    ]
