# Generated by Django 3.1.1 on 2020-12-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0006_subject_current_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='no assigned name', max_length=30)),
                ('ps_threshold', models.FloatField()),
                ('is_subject_play_row', models.BooleanField(default=True)),
                ('cooperation_row', models.FloatField(default=0)),
                ('cooperation_col', models.FloatField(default=0)),
                ('pA_Aa', models.IntegerField(default=1)),
                ('pB_Aa', models.IntegerField(default=2)),
                ('pA_Ab', models.IntegerField(default=3)),
                ('pB_Ab', models.IntegerField(default=4)),
                ('pA_Ba', models.IntegerField(default=5)),
                ('pB_Ba', models.IntegerField(default=6)),
                ('pA_Bb', models.IntegerField(default=7)),
                ('pB_Bb', models.IntegerField(default=8)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='completed_experiments',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='subject',
            name='context_group',
            field=models.CharField(default='trade', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_session',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='current_phase',
            field=models.CharField(default='Consent phase', max_length=30),
        ),
    ]
