# Generated by Django 3.1.1 on 2020-12-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0007_auto_20201224_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematrix',
            name='strategy_a',
            field=models.CharField(default='cooperate', max_length=30),
        ),
        migrations.AddField(
            model_name='gamematrix',
            name='strategy_b',
            field=models.CharField(default='defect', max_length=30),
        ),
    ]
