# Generated by Django 3.1.1 on 2020-12-27 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0008_auto_20201225_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematrix',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profilePresntaion.experimentphase'),
        ),
    ]
