# Generated by Django 3.1.1 on 2020-12-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0010_auto_20201227_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamematrix',
            old_name='experiment',
            new_name='phase',
        ),
    ]
