# Generated by Django 3.1.1 on 2021-01-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0011_auto_20201227_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='is_in_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='off_order_place',
            field=models.CharField(default='irrelevant', max_length=30),
        ),
    ]
