# Generated by Django 3.1.1 on 2021-01-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0012_auto_20210101_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamematrix',
            name='context_group',
            field=models.CharField(default='tutorial', max_length=30),
        ),
    ]
