# Generated by Django 3.1.1 on 2021-01-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0013_gamematrix_context_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='session_1_ps',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='subject',
            name='session_2_ps',
            field=models.FloatField(default=0.5),
        ),
    ]
