# Generated by Django 3.1.1 on 2021-02-04 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0016_auto_20210204_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaritycontextmodel',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.context'),
        ),
    ]
