# Generated by Django 3.1.1 on 2021-03-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0017_auto_20210204_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_artificial',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ArtificialProfileModel',
            fields=[
                ('profilemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profilePresntaion.profilemodel')),
                ('target_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilePresntaion.subject')),
            ],
            bases=('profilePresntaion.profilemodel',),
        ),
    ]
