# Generated by Django 3.1.1 on 2021-03-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilePresntaion', '0019_remove_subject_current_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='current_phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profilePresntaion.experimentphase'),
        ),
    ]
