# Generated by Django 3.2.5 on 2021-07-13 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Neutral', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('phases', models.CharField(default='pre task, post task', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('phase_place', models.IntegerField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_end', models.CharField(default='right', max_length=200)),
                ('left_end', models.CharField(default='left', max_length=200)),
                ('feature_name', models.CharField(default='Name', max_length=200)),
                ('label_set', models.CharField(default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_subject', models.BooleanField(default=False)),
                ('is_artificial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityContextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.context')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_text', models.CharField(default='', max_length=1000)),
                ('int_place', models.IntegerField()),
                ('is_in_order', models.BooleanField(default=True)),
                ('off_order_place', models.CharField(default='irrelevant', max_length=30)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.experiment')),
                ('str_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.experimentphase')),
            ],
        ),
        migrations.CreateModel(
            name='GameMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='no assigned name', max_length=30)),
                ('ps_threshold', models.FloatField()),
                ('is_subject_play_row', models.BooleanField(default=True)),
                ('cooperation_row', models.FloatField(default=0)),
                ('cooperation_col', models.FloatField(default=0)),
                ('strategy_a', models.CharField(default='cooperate', max_length=30)),
                ('strategy_b', models.CharField(default='defect', max_length=30)),
                ('pA_Aa', models.IntegerField(default=1)),
                ('pB_Aa', models.IntegerField(default=2)),
                ('pA_Ab', models.IntegerField(default=3)),
                ('pB_Ab', models.IntegerField(default=4)),
                ('pA_Ba', models.IntegerField(default=5)),
                ('pB_Ba', models.IntegerField(default=6)),
                ('pA_Bb', models.IntegerField(default=7)),
                ('pB_Bb', models.IntegerField(default=8)),
                ('context_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.context')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipa_1_2.experimentphase')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.5)),
                ('feature_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.featurelabels')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.similaritycontextmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('target_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.featurelabels')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('profilemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ipa_1_2.profilemodel')),
                ('trials_string_list', models.CharField(default='', max_length=800)),
                ('trials_responses_list', models.CharField(default='', max_length=800)),
                ('subject_session', models.IntegerField(default=0)),
                ('completed_experiments', models.CharField(default='', max_length=300)),
                ('context_group', models.CharField(default='trade', max_length=50)),
                ('session_1_ps', models.FloatField(default=0.5)),
                ('session_2_ps', models.FloatField(default=0.5)),
                ('current_phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipa_1_2.experimentphase')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.experiment')),
            ],
            bases=('ipa_1_2.profilemodel',),
        ),
        migrations.CreateModel(
            name='ArtificialProfileModel',
            fields=[
                ('profilemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ipa_1_2.profilemodel')),
                ('target_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.subject')),
            ],
            bases=('ipa_1_2.profilemodel',),
        ),
    ]
