# Generated by Django 3.2.5 on 2021-07-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='profile_label_set',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
