# Generated by Django 3.1.1 on 2021-07-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0003_auto_20210719_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='session_1_ps',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='session_2_ps',
        ),
    ]
