# Generated by Django 3.1.1 on 2021-07-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0004_auto_20210719_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='max_similarity_name',
            field=models.CharField(default='not_provided', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_similarity_value',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='subject',
            name='min_similarity_name',
            field=models.CharField(default='not_provided', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='min_similarity_value',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='subject',
            name='completed_experiments',
            field=models.CharField(default='-', max_length=300),
        ),
        migrations.AlterField(
            model_name='subject',
            name='trials_responses_list',
            field=models.CharField(default='-', max_length=800),
        ),
        migrations.AlterField(
            model_name='subject',
            name='trials_string_list',
            field=models.CharField(default='-', max_length=800),
        ),
    ]
