# Generated by Django 3.1.1 on 2021-07-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0005_auto_20210722_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_MinMax',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MinMaxProfileModel',
            fields=[
                ('profilemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ipa_1_2.profilemodel')),
                ('target_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.subject')),
            ],
            bases=('ipa_1_2.profilemodel',),
        ),
    ]
