# Generated by Django 3.1.1 on 2021-08-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0007_subject_profiles_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='instruction_text_female',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='instruction',
            name='instruction_text_male',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='subject',
            name='gender',
            field=models.CharField(default='male', max_length=20),
        ),
    ]
