# Generated by Django 3.1.1 on 2021-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0009_usertosubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_num',
            field=models.CharField(default='not_provided', max_length=50),
        ),
    ]
