# Generated by Django 3.1.1 on 2021-08-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0010_subject_subject_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertosubject',
            name='features_set',
            field=models.CharField(default='A', max_length=100),
        ),
    ]
