# Generated by Django 3.1.1 on 2021-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0011_usertosubject_features_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurelabels',
            name='question_heb',
            field=models.CharField(default='Default question?', max_length=200),
        ),
    ]
