# Generated by Django 3.1.1 on 2021-08-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0013_featurelabels_presenting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='age',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='subject',
            name='identification_profiles',
            field=models.CharField(default='-', max_length=800),
        ),
        migrations.AddField(
            model_name='subject',
            name='identification_rts',
            field=models.CharField(default='-', max_length=800),
        ),
        migrations.AddField(
            model_name='subject',
            name='profiles_response_times',
            field=models.CharField(default='-', max_length=800),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_profile_sides',
            field=models.CharField(default='-', max_length=800),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_reported_sides',
            field=models.CharField(default='-', max_length=800),
        ),
    ]
