# Generated by Django 3.1.1 on 2021-08-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0014_auto_20210816_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurelabels',
            name='question_heb_max_min_ideal',
            field=models.CharField(default='Default question?', max_length=200),
        ),
    ]
