# Generated by Django 3.1.1 on 2021-08-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0015_featurelabels_question_heb_max_min_ideal'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentphase',
            name='n_practice_trials',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='experimentphase',
            name='n_trials',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='experimentphase',
            name='practice_trials_content',
            field=models.CharField(default='0.2,0.5', max_length=1000),
        ),
        migrations.AddField(
            model_name='experimentphase',
            name='trials_content',
            field=models.CharField(default='0.2,0.5', max_length=1000),
        ),
    ]
