# Generated by Django 3.1.1 on 2021-08-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0016_auto_20210820_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='artificialprofilemodel',
            name='target_phase',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.experimentphase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experimentphase',
            name='practice_trials_content',
            field=models.CharField(default='0.2, 0.5', max_length=1000),
        ),
        migrations.AlterField(
            model_name='experimentphase',
            name='trials_content',
            field=models.CharField(default='0.2, 0.5', max_length=1000),
        ),
    ]
