# Generated by Django 3.1.1 on 2021-08-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0018_auto_20210820_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artificialprofilemodel',
            name='target_phase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.experimentphase'),
        ),
        migrations.AlterField(
            model_name='minmaxprofilemodel',
            name='target_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipa_1_2.subject'),
        ),
    ]
