# Generated by Django 3.1.1 on 2021-08-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0019_auto_20210820_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='completed_experiments',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='subject',
            name='identification_profiles',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='identification_rts',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='profiles_response_times',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_profile_sides',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_reported_sides',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='trials_responses_list',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='trials_string_list',
            field=models.TextField(default='-'),
        ),
    ]
