# Generated by Django 3.1.1 on 2021-08-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0020_auto_20210820_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_end', models.CharField(default='right', max_length=200)),
                ('left_end', models.CharField(default='left', max_length=200)),
                ('sham_name', models.CharField(default='Name', max_length=200)),
                ('label_set', models.CharField(default='A', max_length=2)),
                ('question_heb', models.CharField(default='Default question?', max_length=200)),
                ('presenting_name', models.CharField(default='Default Name', max_length=200)),
            ],
        ),
    ]
