# Generated by Django 3.1.1 on 2021-08-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0021_shamquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='pitctures_names',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
