# Generated by Django 3.1.1 on 2021-08-24 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0022_instruction_pitctures_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 9, 48, 34, 532976)),
        ),
        migrations.AddField(
            model_name='subject',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 9, 48, 34, 532976)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='context_group',
            field=models.CharField(default='neutral', max_length=50),
        ),
    ]
