# Generated by Django 3.1.1 on 2021-08-24 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0023_auto_20210824_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 9, 48, 49, 828376)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 9, 48, 49, 828376)),
        ),
    ]
