# Generated by Django 3.1.1 on 2021-08-25 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0024_auto_20210824_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 14, 57, 33, 210008)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 11, 57, 33, 210008, tzinfo=utc)),
        ),
    ]
