# Generated by Django 3.1.1 on 2021-08-25 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0025_auto_20210825_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 12, 49, 18, 422192, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 12, 49, 18, 422192, tzinfo=utc)),
        ),
    ]
