# Generated by Django 3.1.1 on 2021-08-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0026_auto_20210825_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='education',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
