# Generated by Django 3.1.1 on 2021-08-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0027_auto_20210825_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='education',
            field=models.CharField(default='BA', max_length=20),
        ),
    ]
