# Generated by Django 3.1.1 on 2021-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0028_auto_20210825_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertosubject',
            name='age',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='usertosubject',
            name='education',
            field=models.CharField(default='BA', max_length=100),
        ),
    ]
