# Generated by Django 3.1.1 on 2021-08-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0029_auto_20210825_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='trial_features_order',
            field=models.TextField(default='-'),
        ),
    ]
