# Generated by Django 3.1.1 on 2021-08-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0030_subject_trial_features_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureweight',
            name='label_set',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='similaritycontextmodel',
            name='label_set',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
