# Generated by Django 3.1.1 on 2021-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0031_auto_20210829_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertosubject',
            name='gender',
            field=models.CharField(default='female', max_length=100),
        ),
    ]
