# Generated by Django 3.1.1 on 2021-10-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0032_usertosubject_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='feature_response_times',
            field=models.TextField(default='-'),
        ),
    ]
