# Generated by Django 3.1.1 on 2021-10-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0033_subject_feature_response_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='profiles_descriptions',
        ),
    ]
