# Generated by Django 3.1.1 on 2021-10-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0034_remove_subject_profiles_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurelabels',
            old_name='question_heb',
            new_name='question_heb_female',
        ),
        migrations.RenameField(
            model_name='featurelabels',
            old_name='question_heb_max_min_ideal',
            new_name='question_heb_male',
        ),
        migrations.RenameField(
            model_name='shamquestion',
            old_name='question_heb',
            new_name='question_heb_female',
        ),
        migrations.AddField(
            model_name='featurelabels',
            name='question_heb_max_min_ideal_female',
            field=models.CharField(default='Default question?', max_length=200),
        ),
        migrations.AddField(
            model_name='featurelabels',
            name='question_heb_max_min_ideal_male',
            field=models.CharField(default='Default question?', max_length=200),
        ),
        migrations.AddField(
            model_name='shamquestion',
            name='question_heb_male',
            field=models.CharField(default='Default question?', max_length=200),
        ),
    ]
