# Generated by Django 3.1.1 on 2021-10-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0035_auto_20211004_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='n_identification_rounds_allowed',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='subject',
            name='n_identification_task_rounds',
            field=models.IntegerField(default=0),
        ),
    ]
