# Generated by Django 3.1.1 on 2021-10-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0036_auto_20211014_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='runningLocation',
            field=models.CharField(default='Lab', max_length=20),
        ),
        migrations.AddField(
            model_name='usertosubject',
            name='runningLocation',
            field=models.CharField(default='Lab', max_length=20),
        ),
    ]
