# Generated by Django 3.1.1 on 2021-10-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_1_2', '0037_auto_20211018_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='off_order_place',
            field=models.CharField(default='irrelevant', max_length=40),
        ),
    ]
