# Generated by Django 3.1.1 on 2022-09-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='trials_games_names',
            field=models.TextField(default='-'),
        ),
    ]
