# Generated by Django 3.1.1 on 2022-08-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_2', '0002_subject_sets_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='identification_profiles',
            new_name='identification_profiles_left',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='trials_string_list',
            new_name='identification_profiles_right',
        ),
        migrations.AddField(
            model_name='subject',
            name='profile_names_left',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='subject',
            name='profile_names_right',
            field=models.TextField(default='-'),
        ),
    ]
