# Generated by Django 3.1.1 on 2022-11-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_2', '0002_subject_trials_games_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instruction_text',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
