# Generated by Django 3.1.1 on 2022-11-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_2', '0003_auto_20221102_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instruction_text_female',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instruction_text_male',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
