# Generated by Django 3.1.1 on 2022-08-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_2', '0004_remove_subject_feature_response_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='trials_set',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
